# Docker Compose 覆盖配置示例
# 复制为 docker-compose.override.yml 来自定义配置

version: '3.8'

services:
  nas-fan-controller:
    # 调试模式 - 执行一次测试后退出
    # environment:
    #   - RUN_MODE=test
    
    # 发现模式 - 显示硬盘信息后退出  
    # environment:
    #   - RUN_MODE=discover
    
    # 守护进程模式（默认）- 持续运行监控
    environment:
      - RUN_MODE=daemon
    
    # 绿联 NAS 用户配置示例
    # volumes:
    #   - ./fan_config_ugreen.yaml:/app/fan_config.yaml:ro

# 快速测试配置 - 单独使用
# docker-compose -f docker-compose.yml -f docker-compose.test.yml up --rm
---
version: '3.8'

services:
  nas-fan-controller-test:
    image: czcoder/nas-fan-controller:latest
    container_name: nas-fan-controller-test  
    privileged: true
    volumes:
      - /dev:/dev
      - /sys:/sys
      - /proc:/proc:ro
      - ./fan_config.yaml:/app/fan_config.yaml:ro
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
      - RUN_MODE=test  # 测试模式
    # 测试完成后自动删除容器
    restart: "no"
